;;; org-note-org-bridge-capture-test.el --- Org Note Capture bridge tests -*- lexical-binding: t; -*-

;;; Commentary:
;; Focused tests for non-file Capture staging and existing-document PUTs.

;;; Code:

(require 'test-helper)
(require 'gsmlg-org-note-org)
(require 'gsmlg-org)
(require 'org-note-operation)
(require 'json)

(defun gsmlg-org-note-capture-test--document (&rest overrides)
  "Return an active Capture target document with OVERRIDES."
  (append overrides
          '((id . "doc-1")
            (workspace_id . "ws-1")
            (path . "inbox.org")
            (source . "* Existing\n")
            (revision . 4)
            (archived_at . nil))))

(defmacro gsmlg-org-note-capture-test--with-target (&rest body)
  "Run BODY in a configured bridge Capture staging buffer."
  (declare (indent 0) (debug t))
  `(let ((gsmlg-org-note-org-enable t)
         (gsmlg-org-note-capture-workspace-id "ws-1")
         (gsmlg-org-note-capture-document-id "doc-1")
         (gsmlg-org-note-capture-document-path "inbox.org"))
     (with-temp-buffer
       (let ((org-mode-hook nil))
         (org-mode))
       (insert "* NEXT Captured\n")
       ,@body)))

(ert-deftest gsmlg-org-note-capture-reservation-rejects-live-owner ()
  "A reservation owned by a live PID is refused without mutation."
  (let* ((root (make-temp-file "gsmlg-capture-lock-" t))
         (gsmlg-state-directory (file-name-as-directory root))
         (directory (directory-file-name
                     (gsmlg-org-note-org--capture-reservation-directory)))
         (owner-file (expand-file-name "owner.json" directory)))
    (make-directory directory t)
    (set-file-modes directory #o700)
    (with-temp-file owner-file
      (insert (json-serialize `((pid . ,(emacs-pid)) (nonce . "live")))))
    (set-file-modes owner-file #o600)
    (let ((gsmlg-org-note-org--capture-reservation nil))
      (should-error (gsmlg-org-note-org--capture-reservation-acquire)
                    :type 'user-error))))

(ert-deftest gsmlg-org-note-capture-reservation-release-checks-nonce ()
  "A changed owner nonce prevents release of another reservation."
  (let* ((root (make-temp-file "gsmlg-capture-lock-" t))
         (gsmlg-state-directory (file-name-as-directory root))
         (gsmlg-org-note-org--capture-reservation nil))
    (gsmlg-org-note-org--capture-reservation-acquire)
    (let* ((reservation gsmlg-org-note-org--capture-reservation)
           (file (expand-file-name "owner.json"
                                   (plist-get reservation :directory))))
      (with-temp-file file
        (insert (json-serialize '((nonce . "other")))))
      (set-file-modes file #o600)
      (gsmlg-org-note-org--capture-reservation-release)
      (should (file-exists-p file)))))

(ert-deftest gsmlg-org-note-capture-create-accepts-revision-zero ()
  "A pending-create Capture uses one id and accepts committed revision zero."
  (let ((dispatches 0)
        frozen)
    (let ((gsmlg-org-note-org-enable t)
          (gsmlg-org-note-capture-workspace-id "ws-1")
          (gsmlg-org-note-capture-document-id nil)
          (gsmlg-org-note-capture-document-path "inbox.org")
          (gsmlg-org-note-capture-endpoint "https://agent-note.gsmlg.net")
          (gsmlg-org-note-org--capture-reservation nil))
      (with-temp-buffer
        (let ((org-mode-hook nil)) (org-mode))
        (insert "* New capture\n")
        (cl-letf (((symbol-function 'org-note-operation-list-documents)
                   (lambda (&rest _args) '((items . nil) (next_cursor . nil))))
                  ((symbol-function 'completing-read)
                   (lambda (&rest _args) "[Create new document]"))
                  ((symbol-function 'read-string)
                   (lambda (&rest _args) "inbox.org"))
                  ((symbol-function 'org-id-uuid)
                   (lambda () "new-doc-1"))
                  ((symbol-function 'org-note-operation-lease-proofs)
                   (lambda (_id) (make-hash-table :test #'equal)))
                  ((symbol-function 'org-note-client-new-operation-id)
                   (lambda () "create-op-1"))
                  ((symbol-function 'org-note-operation--dispatch-frozen)
                   (lambda (request)
                     (setq dispatches (1+ dispatches) frozen request)
                     '((document_revisions (new-doc-1 . 0))))))
          (gsmlg-org-note-org-capture-before-finalize)
          (should (= dispatches 1))
          (let* ((body (json-parse-string (plist-get frozen :body)
                                          :object-type 'alist))
                 (attempt gsmlg-org-note-org--capture-attempt))
            (should-not (assq 'expected_revision body))
            (should (equal (plist-get attempt :document-id) "new-doc-1"))
            (should (equal gsmlg-org-note-capture-document-id "new-doc-1"))))))))

(ert-deftest gsmlg-org-note-capture-409-keeps-staging-editable ()
  "A definitive path conflict clears the attempt without ambiguity."
  (gsmlg-org-note-capture-test--with-target
    (cl-letf (((symbol-function 'org-note-operation-get-document)
               (lambda (&rest _args) (gsmlg-org-note-capture-test--document)))
              ((symbol-function 'org-note-operation-lease-proofs)
               (lambda (_id) (make-hash-table :test #'equal)))
              ((symbol-function 'org-note-client-new-operation-id)
               (lambda () "conflict-op-1"))
              ((symbol-function 'org-note-operation--dispatch-frozen)
               (lambda (_request)
                 (signal 'org-note-http-error
                         '((:status 409 :code "path_conflict")))))
              ((symbol-function 'gsmlg-org-note-org--capture-journal-write)
               (lambda (&rest _args) nil)))
      (should-error (gsmlg-org-note-org-capture-before-finalize)
                    :type 'org-note-http-error)
      (should-not gsmlg-org-note-org--capture-attempt)
      (should-not buffer-read-only))))

(ert-deftest gsmlg-org-note-capture-recovers-confirmed-dead-owner ()
  "Explicit confirmation recovers a reservation with a dead PID."
  (let* ((root (make-temp-file "gsmlg-capture-lock-" t))
         (gsmlg-state-directory (file-name-as-directory root))
         (gsmlg-org-note-org--capture-reservation nil)
         (directory (directory-file-name
                     (gsmlg-org-note-org--capture-reservation-directory))))
    (make-directory directory t)
    (set-file-modes directory #o700)
    (let ((file (expand-file-name "owner.json" directory)))
      (with-temp-file file
        (insert (json-serialize '((pid . 999999999) (nonce . "dead")))))
      (set-file-modes file #o600))
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _args) t)))
      (gsmlg-org-note-org-recover-capture-reservation))
    (should (plist-get gsmlg-org-note-org--capture-reservation :owner))
    (gsmlg-org-note-org--capture-reservation-release)))

(defmacro gsmlg-org-note-capture-test--with-remote (document dispatch &rest body)
  "Stub DOCUMENT lookup and DISPATCH while evaluating BODY."
  (declare (indent 2) (debug t))
  `(cl-letf (((symbol-function 'org-note-operation-get-document)
              (lambda (_workspace _document) ,document))
             ((symbol-function 'org-note-operation-lease-proofs)
              (lambda (_document) (make-hash-table :test #'equal)))
             ((symbol-function 'org-note-client-new-operation-id)
              (lambda () "capture-op-1"))
             ((symbol-function 'org-note-operation--dispatch-frozen)
              ,dispatch))
     ,@body))

(ert-deftest gsmlg-org-note-capture-templates-preserve-disabled-contract ()
  "Only active bridge templates use non-file targets and omit native clocks."
  (let ((gsmlg-org-directory "/tmp/gsmlg-org-capture-contract/")
        (gsmlg-org-note-org--activated nil))
    (unwind-protect
        (progn
          (gsmlg-org-refresh-capture-templates)
          (should (equal (mapcar (lambda (template) (nth 3 template))
                                 org-capture-templates)
                         '((file "/tmp/gsmlg-org-capture-contract/todo.org")
                           (file "/tmp/gsmlg-org-capture-contract/note.org")
                           (file "/tmp/gsmlg-org-capture-contract/bookmark.org"))))
          (let ((gsmlg-org-note-org--activated t))
            (gsmlg-org-refresh-capture-templates)
            (dolist (template org-capture-templates)
              (should (equal (nth 3 template)
                             '(function gsmlg-org-note-org-capture-target)))
              (should (eq (plist-get (nthcdr 5 template) :no-save) t))
              (should-not (plist-member (nthcdr 5 template) :clock-in))
              (should-not (plist-member (nthcdr 5 template) :clock-keep))
              (should-not (plist-member (nthcdr 5 template) :clock-resume)))))
      (let ((gsmlg-org-note-org--activated nil))
        (gsmlg-org-refresh-capture-templates)))))

(ert-deftest gsmlg-org-note-capture-target-selects-dedicated-non-file-buffer ()
  "The function target must not detach the originating file buffer."
  (with-temp-buffer
    (let ((origin (current-buffer))
          (origin-file "/tmp/origin.org")
          staging)
      (setq buffer-file-name origin-file)
      (unwind-protect
          (progn
            (let ((org-mode-hook nil))
              (gsmlg-org-note-org-capture-target))
            (setq staging (current-buffer))
            (should-not (eq staging origin))
            (should (derived-mode-p 'org-mode))
            (should-not buffer-file-name)
            (should-not buffer-offer-save)
            (with-current-buffer origin
              (should (equal buffer-file-name origin-file))))
        (when (and (buffer-live-p staging) (not (eq staging origin)))
          (kill-buffer staging))
        (set-buffer origin)))))

(ert-deftest gsmlg-org-note-capture-put-freezes-complete-request-once ()
  "Existing-target Capture freezes one identified revision-bound PUT."
  (let ((dispatches nil)
        (operation-id-calls 0))
    (gsmlg-org-note-capture-test--with-target
      (cl-letf (((symbol-function 'org-note-operation-get-document)
                 (lambda (_workspace _document)
                   (gsmlg-org-note-capture-test--document)))
                ((symbol-function 'org-note-operation-lease-proofs)
                 (lambda (_document) (make-hash-table :test #'equal)))
                ((symbol-function 'org-note-client-new-operation-id)
                 (lambda ()
                   (cl-incf operation-id-calls)
                   "capture-op-1"))
                ((symbol-function 'org-note-operation--dispatch-frozen)
                 (lambda (frozen)
                   (push frozen dispatches)
                   '((document_revisions . ((doc-1 . 5)))))))
        (gsmlg-org-note-org-capture-before-finalize)
        (gsmlg-org-note-org-capture-before-finalize)
        (should (= operation-id-calls 1))
        (should (= (length dispatches) 1))
        (let* ((frozen (car dispatches))
               (body (json-parse-string
                      (decode-coding-string (plist-get frozen :body) 'utf-8)
                      :object-type 'alist :array-type 'list
                      :null-object nil :false-object :json-false)))
          (should (equal (plist-get frozen :method) "PUT"))
          (should (equal (plist-get frozen :route)
                         "/api/org/documents/doc-1"))
          (should (equal (alist-get 'workspace_id body) "ws-1"))
          (should (equal (alist-get 'operation_id body) "capture-op-1"))
          (should (equal (alist-get 'path body) "inbox.org"))
          (should (equal (alist-get 'source body)
                         "* Existing\n* NEXT Captured\n"))
          (should (= (alist-get 'expected_revision body) 4))
          (should (string-match-p
                   "\\\"lease_proofs\\\":{}"
                   (decode-coding-string (plist-get frozen :body) 'utf-8))))
        (should (eq (plist-get gsmlg-org-note-org--capture-attempt :state)
                    'committed))))))

(ert-deftest gsmlg-org-note-capture-refuses-invalid-target-before-freeze ()
  "Identity, path, archive, source, and revision failures cannot freeze a PUT."
  (dolist (override '(((id . "doc-other"))
                      ((workspace_id . "ws-other"))
                      ((path . "other.org"))
                      ((source . 9))
                      ((revision . -1))
                      ((revision . 1.5))
                      ((archived_at . 42))
                      ((archived_at . "bad"))))
    (let ((freezes 0)
          (dispatches 0))
      (gsmlg-org-note-capture-test--with-target
        (cl-letf (((symbol-function 'org-note-operation-get-document)
                   (lambda (_workspace _document)
                     (apply #'gsmlg-org-note-capture-test--document override)))
                  ((symbol-function 'org-note-operation--freeze-request)
                   (lambda (_typed) (cl-incf freezes)))
                  ((symbol-function 'org-note-operation--dispatch-frozen)
                   (lambda (_frozen) (cl-incf dispatches))))
          (should-error (gsmlg-org-note-org-capture-before-finalize)
                        :type 'user-error)
          (should (= freezes 0))
          (should (= dispatches 0)))))))

(ert-deftest gsmlg-org-note-capture-refuses-lease-before-freeze ()
  "A nonempty proof object prevents Capture freezing and dispatch."
  (let ((proofs (make-hash-table :test #'equal))
        (freezes 0)
        (dispatches 0))
    (puthash "item-1" '((fencing_token . "secret")) proofs)
    (gsmlg-org-note-capture-test--with-target
      (cl-letf (((symbol-function 'org-note-operation-get-document)
                 (lambda (_workspace _document)
                   (gsmlg-org-note-capture-test--document)))
                ((symbol-function 'org-note-operation-lease-proofs)
                 (lambda (_document) proofs))
                ((symbol-function 'org-note-operation--freeze-request)
                 (lambda (_typed) (cl-incf freezes)))
                ((symbol-function 'org-note-operation--dispatch-frozen)
                 (lambda (_frozen) (cl-incf dispatches))))
        (should-error (gsmlg-org-note-org-capture-before-finalize)
                      :type 'user-error)
        (should (= freezes 0))
        (should (= dispatches 0))))))

(ert-deftest gsmlg-org-note-capture-requires-strictly-advanced-revision ()
  "Missing, wrong-type, and non-advanced PUT revisions remain ambiguous."
  (dolist (response '(((document_revisions . ((doc-1 . 4))))
                      ((document_revisions . ((doc-1 . "5"))))
                      ((document_revisions . ((other . 5))))
                      ((document_revisions . ((doc-1 . 4.5))))))
    (gsmlg-org-note-capture-test--with-target
      (gsmlg-org-note-capture-test--with-remote
          (gsmlg-org-note-capture-test--document)
          (lambda (_frozen) response)
        (should-error (gsmlg-org-note-org-capture-before-finalize)
                      :type 'user-error)
        (should (eq (plist-get gsmlg-org-note-org--capture-attempt :state)
                    'ambiguous))
        (should buffer-read-only)))))

(ert-deftest gsmlg-org-note-capture-detects-post-commit-divergence ()
  "A staging edit during dispatch is retained without replay after commit."
  (let ((dispatches 0))
    (gsmlg-org-note-capture-test--with-target
      (gsmlg-org-note-capture-test--with-remote
          (gsmlg-org-note-capture-test--document)
          (lambda (_frozen)
            (cl-incf dispatches)
            (goto-char (point-max))
            (insert "changed during dispatch\n")
            '((document_revisions . ((doc-1 . 5)))))
        (should-error (gsmlg-org-note-org-capture-before-finalize)
                      :type 'user-error)
        (should (= dispatches 1))
        (should (eq (plist-get gsmlg-org-note-org--capture-attempt :state)
                    'committed-local-divergence))
        (should buffer-read-only)
        (should-error (gsmlg-org-note-org-capture-before-finalize)
                      :type 'user-error)
        (should (= dispatches 1))))))

(ert-deftest gsmlg-org-note-capture-post-dispatch-error-is-replayable ()
  "An ambiguous Capture PUT must retry its exact frozen envelope."
  (let ((dispatches nil)
        (operation-id-calls 0))
    (gsmlg-org-note-capture-test--with-target
      (cl-letf (((symbol-function 'org-note-operation-get-document)
                 (lambda (_workspace _document)
                   (gsmlg-org-note-capture-test--document)))
                ((symbol-function 'org-note-operation-lease-proofs)
                 (lambda (_document) (make-hash-table :test #'equal)))
                ((symbol-function 'org-note-client-new-operation-id)
                 (lambda ()
                   (cl-incf operation-id-calls)
                   "capture-op-1"))
                ((symbol-function 'org-note-operation--dispatch-frozen)
                 (lambda (frozen)
                   (push frozen dispatches)
                   (if (= (length dispatches) 1)
                       (signal 'org-note-transport-error '("uncertain"))
                     '((document_revisions . ((doc-1 . 5))))))))
        (should-error (gsmlg-org-note-org-capture-before-finalize)
                      :type 'org-note-transport-error)
        (should (eq (plist-get gsmlg-org-note-org--capture-attempt :state)
                    'ambiguous))
        (should buffer-read-only)
        (let ((frozen (plist-get gsmlg-org-note-org--capture-attempt :frozen)))
          (gsmlg-org-note-org-retry-ambiguous-capture)
          (should (= operation-id-calls 1))
          (should (= (length dispatches) 2))
          (should (eq (nth 0 dispatches) frozen))
          (should (eq (nth 1 dispatches) frozen))
          (should (eq (plist-get gsmlg-org-note-org--capture-attempt :state)
                      'committed)))))))

(provide 'org-note-org-bridge-capture-test)
;;; org-note-org-bridge-capture-test.el ends here
