;;; org-note-org-bridge-phase7-test.el --- Phase 7 hardening tests -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'gsmlg-org-note-org)
(defvar org-note-endpoint)

(ert-deftest gsmlg-org-note-org-phase7-default-disabled ()
  (should-not gsmlg-org-note-org-enable))

(ert-deftest gsmlg-org-note-org-phase7-install-guards-is-top-level ()
  (should (fboundp 'gsmlg-org-note-org-install-guards)))

(ert-deftest gsmlg-org-note-org-phase7-publication-key-isolated ()
  (let* ((org-note-endpoint "https://agent-note.example/a")
         (a (gsmlg-org-note-org--publication-reservation-directory '("one")))
         (b (gsmlg-org-note-org--publication-reservation-directory '("two")))
         (c (gsmlg-org-note-org--publication-reservation-directory '("three"))))
    (should-not (equal a b))
    (should-not (equal a c))))

(ert-deftest gsmlg-org-note-org-phase7-owner-start-token-field ()
  (let ((gsmlg-org-note-org--capture-reservation nil)
        (root (make-temp-file "org-note-phase7-" t)))
    (cl-letf (((symbol-function 'gsmlg-state-file)
               (lambda (&rest parts) (expand-file-name (car parts) root)))
              ((symbol-function 'org-note-client-new-operation-id)
               (lambda () "phase7-nonce")))
      (gsmlg-org-note-org--capture-reservation-acquire)
      (unwind-protect
          (let* ((file (expand-file-name "owner.json"
                                         (plist-get gsmlg-org-note-org--capture-reservation
                                                    :directory)))
                 (owner (json-parse-string
                         (with-temp-buffer
                           (insert-file-contents-literally file)
                           (buffer-string))
                         :object-type 'alist)))
            (should (integerp (alist-get 'pid owner)))
            (should (stringp (alist-get 'nonce owner)))
            (should (assq 'start_token owner)))
        (gsmlg-org-note-org--capture-reservation-release)))))

(ert-deftest gsmlg-org-note-org-phase7-ownerless-grace-refuses ()
  (let* ((gsmlg-org-note-org--capture-reservation nil)
         (gsmlg-org-note-org-reservation-ownerless-grace 60.0)
         (root (make-temp-file "org-note-phase7-" t))
         (directory (expand-file-name "org-note/capture.lock" root)))
    (make-directory directory t)
    (cl-letf (((symbol-function 'gsmlg-state-file)
               (lambda (&rest _parts) (concat directory "/"))))
      (should-error (gsmlg-org-note-org--capture-reservation-acquire)
                    :type 'user-error))))

(ert-deftest gsmlg-org-note-org-phase7-publication-second-acquire-refuses ()
  (let* ((org-note-endpoint "https://agent-note.example/a")
         (root (make-temp-file "org-note-phase7-pub-" t))
         (workspace-ids '("workspace"))
         (gsmlg-org-note-org--publication-reservation nil))
    (cl-letf (((symbol-function 'gsmlg-state-file)
               (lambda (&rest parts)
                 (expand-file-name (mapconcat #'identity parts "/") root)))
              ((symbol-function 'org-note-client-new-operation-id)
               (lambda () "publication-nonce")))
      (gsmlg-org-note-org--publication-acquire workspace-ids)
      (let ((first gsmlg-org-note-org--publication-reservation))
        (setq gsmlg-org-note-org--publication-reservation nil)
        (should-error (gsmlg-org-note-org--publication-acquire workspace-ids)
                      :type 'user-error)
        (setq gsmlg-org-note-org--publication-reservation first)
        (gsmlg-org-note-org--publication-release)))))

(ert-deftest gsmlg-org-note-org-phase7-publication-live-owner-without-start-refuses ()
  "Treat a live owner as live when only its volatile etime is available."
  (let* ((org-note-endpoint "https://agent-note.example/a")
         (root (make-temp-file "org-note-phase7-pub-" t))
         (workspace-ids '("workspace"))
         (attribute-read 0)
         (gsmlg-org-note-org--publication-reservation nil))
    (cl-letf (((symbol-function 'gsmlg-state-file)
               (lambda (&rest parts)
                 (expand-file-name (mapconcat #'identity parts "/") root)))
              ((symbol-function 'org-note-client-new-operation-id)
               (lambda () "publication-nonce"))
              ((symbol-function 'process-attributes)
               (lambda (pid)
                 (setq attribute-read (1+ attribute-read))
                 `((pid . ,pid) (etime . ,(format "%d" attribute-read))))))
      (gsmlg-org-note-org--publication-acquire workspace-ids)
      (let ((first gsmlg-org-note-org--publication-reservation))
        (setq gsmlg-org-note-org--publication-reservation nil)
        (should-error (gsmlg-org-note-org--publication-acquire workspace-ids)
                      :type 'user-error)
        (setq gsmlg-org-note-org--publication-reservation first)
        (gsmlg-org-note-org--publication-release)))))

(ert-deftest gsmlg-org-note-org-phase7-publication-release-checks-nonce ()
  (let* ((org-note-endpoint "https://agent-note.example/a")
         (root (make-temp-file "org-note-phase7-pub-" t))
         (workspace-ids '("workspace"))
         (gsmlg-org-note-org--publication-reservation nil))
    (cl-letf (((symbol-function 'gsmlg-state-file)
               (lambda (&rest parts)
                 (expand-file-name (mapconcat #'identity parts "/") root)))
              ((symbol-function 'org-note-client-new-operation-id)
               (lambda () "publication-nonce")))
      (gsmlg-org-note-org--publication-acquire workspace-ids)
      (let* ((reservation gsmlg-org-note-org--publication-reservation)
             (directory (plist-get reservation :directory))
             (owner-file (expand-file-name "owner.json" directory)))
        (with-temp-file owner-file
          (insert (json-serialize '((nonce . "different")))))
        (gsmlg-org-note-org--publication-release)
        (should gsmlg-org-note-org--publication-reservation)
        (should (file-directory-p directory))
        (with-temp-file owner-file
          (insert (json-serialize (plist-get reservation :owner))))
        (gsmlg-org-note-org--publication-release)
        (should-not gsmlg-org-note-org--publication-reservation)
        (should-not (file-exists-p directory))))))

(ert-deftest gsmlg-org-note-org-phase7-publication-cross-process-race ()
  "Prove that two independent Emacs processes cannot own one publication lock."
  (let* ((root (make-temp-file "org-note-phase7-race-" t))
         (script (expand-file-name "race-child.el" root))
         (go (expand-file-name "go" root))
         (result-a (expand-file-name "result-a" root))
         (result-b (expand-file-name "result-b" root))
         (emacs (or (executable-find "emacs")
                    (error "Emacs executable is unavailable")))
         (child-source
          "(let* ((root (car command-line-args-left))
                  (go (expand-file-name \"go\" root))
                  (result (expand-file-name (cadr command-line-args-left) root)))
             (require 'gsmlg-org-note-org)
             (setq org-note-endpoint \"https://agent-note.race.example\")
             (fset 'gsmlg-state-file
                   (lambda (&rest parts)
                     (expand-file-name (mapconcat #'identity parts \"/\") root)))
             (fset 'org-note-client-new-operation-id
                   (lambda () (format \"race-%s\" (emacs-pid))))
             (while (not (file-exists-p go)) (sleep-for 0.01))
             (condition-case nil
                 (progn
                   (gsmlg-org-note-org--publication-acquire '(\"workspace\"))
                   (with-temp-file result (insert \"acquired\\n\"))
                   (sleep-for 0.30)
                   (gsmlg-org-note-org--publication-release))
               (error
                (with-temp-file result (insert \"refused\\n\")))))"))
    (unwind-protect
        (progn
          (with-temp-file script (insert child-source))
          (let* ((args-a (list "-Q" "--batch" "-L" "emacs.d/lisp"
                               "-l" script root "result-a"))
                 (args-b (list "-Q" "--batch" "-L" "emacs.d/lisp"
                               "-l" script root "result-b"))
                 (process-a (apply #'start-process "org-note-race-a" nil emacs args-a))
                 (process-b (apply #'start-process "org-note-race-b" nil emacs args-b))
                 (deadline (+ (float-time) 10.0)))
            (with-temp-file go (insert "start\n"))
            (while (and (< (float-time) deadline)
                        (or (process-live-p process-a)
                            (process-live-p process-b)))
              (accept-process-output process-a 0.05)
              (accept-process-output process-b 0.05))
            (unless (and (not (process-live-p process-a))
                         (not (process-live-p process-b)))
              (delete-process process-a)
              (delete-process process-b)
              (ert-fail "Publication race child processes did not exit"))
            (let ((results (mapcar (lambda (file)
                                    (when (file-readable-p file)
                                      (string-trim
                                       (with-temp-buffer
                                         (insert-file-contents file)
                                         (buffer-string)))))
                                  (list result-a result-b))))
              (should (= 1 (cl-count "acquired" results :test #'equal)))
              (should (= 1 (cl-count "refused" results :test #'equal))))))
      (ignore-errors (delete-directory root t)))))

(provide 'org-note-org-bridge-phase7-test)
;;; org-note-org-bridge-phase7-test.el ends here
